- name: variables
  hosts: local
  connection: local
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "Course is DevOpswith AWS, Duration is 120 hours, Trainee is Vidyasaranya"
      
