- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "DevOps with AWS"
    DURATION: 120HRS
    TRAINEE: Vidyasaranya
  tasks:
  - name: print the variable
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainee is {{ TRAINEE }}"

  - name: print the variables1
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainee is {{ TRAINEE }}"