- name: variables from files
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: Please enter course name
    private: false
  - name: DURATION
    prompt: Please enter duration
    private: false
  - name: TRAINEE
    prompt: Please enter trainee name
    private: false
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainee is {{ TRAINEE }}"