- name: filters
  hosts: local
  connection: local
  tasks: 
  - name: handle undefine variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Satish') }}"
  
- name: convert string to list
  vars:
    fruits: "mango, papaya, banana"
  ansible.builtin.debug:
     msg: "Fruits are: {{ fruits | split(',') }}"